### ISSUE TITLE
Styleguide Metaissue

### ISSUE THREAD

**Issue by dwinkler1** [danielw2904/mixtape#3]
I'd like to clarify some style decisions and discuss them here.
Should we use [DataFramesMeta](https://github.com/JuliaData/DataFramesMeta.jl) or stick to just DataFrames? 
Personally, I have very little experience with Meta but it would be closer to the original implementation using the tidyverse I guess.

**Comment by akulumbeg** [comment]
From what I found on Discourse and some forums, DF's functions are slowly devouring DFM's features. So far, everything I did was only in DF and it worked similarly to dplyr, DFM has more SQLesque syntax which is not used in the original of the book. I would prefer sticking to DF because of that and also because the "futureproofing" of the code.

**Comment by akulumbeg** [comment]
Also, I think this issue can be closed.
